workflows:
  android-build:
    name: Build Android APK
    max_build_duration: 15
    environment:
      flutter: stable
      xcode: latest
      vars:
        PACKAGE_NAME: "com.rashd.app"
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
